project:
  type: website
  output-dir: docs
  
website:
  title: "Página Biblioteca UGR"
  navbar:
    left:
      - href: index.qmd
        text: Biblioteca UGR
      - href: about.qmd
        text: AESDE 

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual